GET  http://localhost:5000/AdminPanelUsers


###
POST http://localhost:5000/login 
Content-Type: application/json

{
"email": "nikitapande00@gmail.com", "password": "QWERTY"
}

###
DELETE http://localhost:5000/demorequests/5f055832227e2b19e8f5613f



